# =============================================================================
# 05_figures.R
# Publication-Quality Figures for Marijuana Legalization DiDisc Paper
# =============================================================================

source("00_packages.R")

# Load results
qwi_border <- readRDS(file.path(data_dir, "qwi_border.rds"))
treatment_dates <- readRDS(file.path(data_dir, "treatment_dates.rds"))
main_results <- readRDS(file.path(data_dir, "main_results.rds"))
industry_df <- readRDS(file.path(data_dir, "industry_results.rds"))

# Load event study results - must be generated by 03_main_analysis.R
if (!file.exists(file.path(data_dir, "event_study_results.rds"))) {
  stop("event_study_results.rds not found. Run 03_main_analysis.R first.")
}
es_coefs <- readRDS(file.path(data_dir, "event_study_results.rds"))

cat("=== Generating Figures ===\n")

# =============================================================================
# Figure 1: Treatment Map
# =============================================================================

cat("Figure 1: Treatment Map\n")

# Load state shapefile
states_sf <- readRDS(file.path(data_dir, "states_sf.rds"))

# Create treatment categories
state_treatment <- tibble(
  STATEFP = c("08", "53", "41", "32", "06", "25", "26", "17"),
  retail_year = c(2014, 2014, 2015, 2017, 2018, 2018, 2019, 2020)
) %>%
  mutate(category = case_when(
    retail_year == 2014 ~ "2014 (CO, WA)",
    retail_year == 2015 ~ "2015 (OR)",
    retail_year %in% 2016:2017 ~ "2016-17 (NV)",
    retail_year == 2018 ~ "2018 (CA, MA)",
    TRUE ~ "2019-20 (MI, IL)"
  ))

# Merge
map_data <- states_sf %>%
  left_join(state_treatment, by = "STATEFP") %>%
  mutate(
    category = ifelse(is.na(category), "Control", category),
    category = factor(category, levels = c("2014 (CO, WA)", "2015 (OR)", "2016-17 (NV)",
                                            "2018 (CA, MA)", "2019-20 (MI, IL)", "Control"))
  )

fig1 <- ggplot(map_data) +
  geom_sf(aes(fill = category), color = "white", linewidth = 0.3) +
  scale_fill_manual(
    values = c(
      "2014 (CO, WA)" = "#1a9850",
      "2015 (OR)" = "#91cf60",
      "2016-17 (NV)" = "#d9ef8b",
      "2018 (CA, MA)" = "#fee08b",
      "2019-20 (MI, IL)" = "#fc8d59",
      "Control" = "gray85"
    ),
    name = "Retail Opening"
  ) +
  labs(
    title = "Recreational Marijuana Legalization: Staggered Adoption",
    subtitle = "Retail opening dates for states in analysis sample"
  ) +
  theme_void() +
  theme(
    legend.position = "bottom",
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 10, color = "gray40")
  )

ggsave(file.path(fig_dir, "fig1_treatment_map.pdf"), fig1, width = 10, height = 6)
ggsave(file.path(fig_dir, "fig1_treatment_map.png"), fig1, width = 10, height = 6, dpi = 300)

# =============================================================================
# Figure 2: Raw Trends by Treatment Status
# =============================================================================

cat("Figure 2: Raw Trends\n")

# Aggregate to quarter × treatment status
trends_data <- qwi_border %>%
  filter(industry == "00", in_bandwidth) %>%
  group_by(date, treated) %>%
  summarise(
    mean_earn = mean(EarnHirAS, na.rm = TRUE),
    se_earn = sd(EarnHirAS, na.rm = TRUE) / sqrt(n()),
    n = n(),
    .groups = "drop"
  ) %>%
  mutate(group = ifelse(treated, "Treated Border Counties", "Control Border Counties"))

# Vertical lines for treatment cohorts
cohort_dates <- treatment_dates %>%
  select(state_abbr, retail_date) %>%
  distinct()

fig2 <- ggplot(trends_data, aes(x = date, y = mean_earn, color = group)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = mean_earn - 1.96*se_earn, ymax = mean_earn + 1.96*se_earn,
                  fill = group), alpha = 0.2, color = NA) +
  geom_vline(data = cohort_dates, aes(xintercept = retail_date),
             linetype = "dashed", color = "gray50", alpha = 0.5) +
  scale_color_manual(values = c("Treated Border Counties" = "#E41A1C",
                                 "Control Border Counties" = "#377EB8")) +
  scale_fill_manual(values = c("Treated Border Counties" = "#E41A1C",
                                "Control Border Counties" = "#377EB8")) +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(
    title = "Average New Hire Earnings at State Borders",
    subtitle = "Counties within 100km of treated/control state borders",
    x = NULL,
    y = "Mean Monthly Earnings (New Hires)",
    color = NULL, fill = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")

ggsave(file.path(fig_dir, "fig2_raw_trends.pdf"), fig2, width = 10, height = 6)
ggsave(file.path(fig_dir, "fig2_raw_trends.png"), fig2, width = 10, height = 6, dpi = 300)

# =============================================================================
# Figure 3: Event Study
# =============================================================================

cat("Figure 3: Event Study\n")

fig3 <- ggplot(es_coefs, aes(x = event_time, y = coef)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  geom_vline(xintercept = -0.5, linetype = "dashed", color = "red", alpha = 0.5) +
  geom_ribbon(aes(ymin = coef - 1.96*se, ymax = coef + 1.96*se),
              fill = "steelblue", alpha = 0.2) +
  geom_line(color = "steelblue", linewidth = 0.8) +
  geom_point(color = "steelblue", size = 2) +
  annotate("text", x = -6, y = max(es_coefs$coef + 1.96*es_coefs$se) * 0.9,
           label = "Pre-Treatment", hjust = 0.5, size = 3, color = "gray40") +
  annotate("text", x = 6, y = max(es_coefs$coef + 1.96*es_coefs$se) * 0.9,
           label = "Post-Retail", hjust = 0.5, size = 3, color = "gray40") +
  scale_x_continuous(breaks = seq(-12, 12, by = 4)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(
    title = "Dynamic Effects of Marijuana Legalization on New Hire Earnings",
    subtitle = "DiDisc event study coefficients; reference period = Q-1 before retail opening",
    x = "Quarters Relative to Retail Opening",
    y = "Effect on Log Earnings"
  ) +
  theme_minimal()

ggsave(file.path(fig_dir, "fig3_event_study.pdf"), fig3, width = 10, height = 6)
ggsave(file.path(fig_dir, "fig3_event_study.png"), fig3, width = 10, height = 6, dpi = 300)

# =============================================================================
# Figure 4: Placebo Tests
# =============================================================================

cat("Figure 4: Placebo Tests\n")

if (exists("main_results") && !is.null(main_results$placebo)) {
  placebo_df <- main_results$placebo

  fig4 <- ggplot(placebo_df, aes(x = event_time, y = tau)) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
    geom_errorbar(aes(ymin = tau - 1.96*se, ymax = tau + 1.96*se),
                  width = 0.5, color = "gray40") +
    geom_point(size = 3, color = "steelblue") +
    scale_x_continuous(breaks = seq(-18, -2, by = 2)) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    labs(
      title = "Placebo Tests: Pre-Treatment Discontinuity Changes",
      subtitle = "Each point: estimated change in border discontinuity between Q(t-2) and Q(t)",
      x = "Quarters Before Retail Opening",
      y = "Placebo Treatment Effect"
    ) +
    theme_minimal()

  ggsave(file.path(fig_dir, "fig4_placebo_tests.pdf"), fig4, width = 10, height = 6)
  ggsave(file.path(fig_dir, "fig4_placebo_tests.png"), fig4, width = 10, height = 6, dpi = 300)
}

# =============================================================================
# Figure 5: Industry Heterogeneity
# =============================================================================

cat("Figure 5: Industry Heterogeneity\n")

if (nrow(industry_df) > 0) {
  # Order by effect size
  industry_df <- industry_df %>%
    mutate(industry_name = fct_reorder(industry_name, tau))

  fig5 <- ggplot(industry_df, aes(x = tau, y = industry_name, color = category)) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "gray50") +
    geom_errorbarh(aes(xmin = tau - 1.96*se, xmax = tau + 1.96*se),
                   height = 0.3, linewidth = 0.8) +
    geom_point(aes(shape = significant_fdr), size = 3) +
    scale_shape_manual(values = c("TRUE" = 16, "FALSE" = 1),
                       labels = c("TRUE" = "FDR < 0.05", "FALSE" = "n.s.")) +
    scale_color_viridis_d(option = "D") +
    scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
    labs(
      title = "Industry-Specific Effects of Marijuana Legalization",
      subtitle = "DiDisc estimates with Benjamini-Hochberg FDR correction",
      x = "Effect on Log New Hire Earnings",
      y = NULL,
      color = "Industry Category",
      shape = "Significance"
    ) +
    theme_minimal() +
    theme(legend.position = "right")

  ggsave(file.path(fig_dir, "fig5_industry_effects.pdf"), fig5, width = 12, height = 8)
  ggsave(file.path(fig_dir, "fig5_industry_effects.png"), fig5, width = 12, height = 8, dpi = 300)
}

# =============================================================================
# Figure 6: Bandwidth Sensitivity
# =============================================================================

cat("Figure 6: Bandwidth Sensitivity\n")

if (exists("main_results") && !is.null(main_results$bandwidth_sensitivity)) {
  bw_df <- main_results$bandwidth_sensitivity

  fig6 <- ggplot(bw_df, aes(x = bandwidth, y = tau)) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
    geom_ribbon(aes(ymin = tau - 1.96*se, ymax = tau + 1.96*se),
                fill = "steelblue", alpha = 0.2) +
    geom_line(color = "steelblue", linewidth = 1) +
    geom_point(color = "steelblue", size = 3) +
    scale_x_continuous(breaks = bw_df$bandwidth) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    labs(
      title = "Bandwidth Sensitivity of DiDisc Estimates",
      subtitle = "Effect estimate by maximum distance from state border (km)",
      x = "Bandwidth (km from border)",
      y = "Treatment Effect (log points)"
    ) +
    theme_minimal()

  ggsave(file.path(fig_dir, "fig6_bandwidth_sensitivity.pdf"), fig6, width = 10, height = 6)
  ggsave(file.path(fig_dir, "fig6_bandwidth_sensitivity.png"), fig6, width = 10, height = 6, dpi = 300)
}

# =============================================================================
# Figure 7: Border-by-Border Heterogeneity
# =============================================================================

cat("Figure 7: Border Heterogeneity\n")

if (exists("main_results") && !is.null(main_results$border_heterogeneity) && nrow(main_results$border_heterogeneity) > 0) {
  border_df <- main_results$border_heterogeneity %>%
    mutate(border_pair = fct_reorder(border_pair, tau))

  fig7 <- ggplot(border_df, aes(x = tau, y = border_pair)) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "gray50") +
    geom_errorbarh(aes(xmin = ci_low, xmax = ci_high),
                   height = 0.3, linewidth = 0.8, color = "steelblue") +
    geom_point(size = 3, color = "steelblue") +
    scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
    labs(
      title = "Treatment Effects by Border Pair",
      subtitle = "DiDisc estimates for each treated-control state border",
      x = "Effect on Log New Hire Earnings",
      y = "Border Pair (Treated-Control)"
    ) +
    theme_minimal()

  ggsave(file.path(fig_dir, "fig7_border_heterogeneity.pdf"), fig7, width = 10, height = 8)
  ggsave(file.path(fig_dir, "fig7_border_heterogeneity.png"), fig7, width = 10, height = 8, dpi = 300)
}

# =============================================================================
# Figure 8: RDD Visualization
# =============================================================================

cat("Figure 8: RDD Visualization\n")

# Binned means by distance
rdd_binned <- qwi_border %>%
  filter(industry == "00", in_bandwidth, post) %>%
  mutate(
    dist_bin = cut(dist_km, breaks = seq(-100, 100, by = 10)),
    treated_fac = factor(treated, levels = c(0, 1), labels = c("Control", "Treated"))
  ) %>%
  group_by(dist_bin, treated_fac) %>%
  summarise(
    mean_earn = mean(log_earn_hire, na.rm = TRUE),
    se_earn = sd(log_earn_hire, na.rm = TRUE) / sqrt(n()),
    dist_midpoint = mean(dist_km),
    n = n(),
    .groups = "drop"
  )

fig8 <- ggplot(rdd_binned, aes(x = dist_midpoint, y = mean_earn)) +
  geom_vline(xintercept = 0, linetype = "solid", color = "gray30") +
  geom_point(aes(color = treated_fac), size = 3, alpha = 0.8) +
  geom_smooth(data = filter(rdd_binned, dist_midpoint < 0),
              method = "lm", se = TRUE, color = "#377EB8", fill = "#377EB8", alpha = 0.2) +
  geom_smooth(data = filter(rdd_binned, dist_midpoint > 0),
              method = "lm", se = TRUE, color = "#E41A1C", fill = "#E41A1C", alpha = 0.2) +
  scale_color_manual(values = c("Treated" = "#E41A1C", "Control" = "#377EB8")) +
  labs(
    title = "Spatial RDD: Log Earnings by Distance to Border (Post-Treatment)",
    subtitle = "Binned means with linear fit; vertical line = state border",
    x = "Signed Distance to Border (km, positive = treated side)",
    y = "Mean Log New Hire Earnings",
    color = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")

ggsave(file.path(fig_dir, "fig8_rdd_visualization.pdf"), fig8, width = 10, height = 6)
ggsave(file.path(fig_dir, "fig8_rdd_visualization.png"), fig8, width = 10, height = 6, dpi = 300)

cat("\n=== All Figures Generated ===\n")
cat("Saved to:", fig_dir, "\n")
